// Interface creada para definir el modelo de Pokemon según "https://pokeapi.co/" y generar la BD de prueba

// Generated by https://quicktype.io

export interface PokeResponse {
    count:    number;
    next:     string;
    previous: null;
    results:  Result[];
}

export interface Result {
    name: string;
    url:  string;
}
